exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('books').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('books').insert({id: 1, title: 'All of Us: The Collected Poems', synopsis: 'This prodigiously rich collection suggests that Raymond Carver was not only America’s finest writer of short fiction, but also one of its most large-hearted and affecting poets. Like Carver’s stories, the more than 00 poems in All of Us are marked by a keen attention to the physical world; an uncanny ability to compress vast feeling into discreet moments; a voice of conversational intimacy, and an unstinting sympathy.',genre_id:2, cover_art: '/images/all of us the collected poems.jpg', isbn: '978-1-86-046168-2'}),
        knex('books').insert({id: 2, title: 'Autobiography of Red', synopsis: 'The award-winning poet Anne Carson reinvents a genre in Autobiography of Red, a stunning work that is both a novel and a poem, both an unconventional re-creation of an ancient Greek myth and a wholly original coming-of-age story set in the present.', genre_id:2 , cover_art: 'images/autobiography of red.jpg', isbn: '978-0-37-570129-0'}),
        knex('books').insert({id: 3, title: 'Being and Nothingness', synopsis: 'Being & Nothingness is without doubt one of the most significant philosophical books of the 20th century. The central work by one of the centurys most influential thinkers, it altered the course of western philosophy. It is one of those rare books whose influence has affected the mindset of subsequent generations. Seventy years after its 1st publication, its message remains as potent as ever--challenging readers to confront the fundamental dilemmas of human freedom, choice, responsibility & action.', genre_id:4, cover_art: 'images/being and nothingness.jpg', isbn: '978-0-67-186780-5'}),
        knex('books').insert({id: 4, title: 'Collected Poems', synopsis: 'This volume contains all Sylvia Plaths mature poetry written from 1genre_id:56 up to her death in 1genre_id:6. The text is preceded by an introduction by Ted Hughes and followed by notes and comments on individual poems. There is also an appendix containing fifty poems from Sylvia Plaths juvenilia. This collection was awarded the 1genre_id:81 Pulitzer Prize for poetry.', genre_id:1, cover_art: 'images/collected poems.jpg', isbn: '978-0-06-155889-4'}),
        knex('books').insert({id: 5, title: 'Complete Maus', synopsis: 'Combined for the first time here are Maus I: A Survivors Tale and Maus II - the complete story of Vladek Spiegelman and his wife, living and surviving in Hitlers Europe. By addressing the horror of the Holocaust through cartoons, the genre_id captures the everyday reality of fear and is able to explore the guilt, relief and extraordinary sensation of survival - and how the children of survivors are in their own way affected by the trials of their parents. A contemporary classic of immeasurable significance.', genre_id:5, cover_art: 'images/complete maus.jpg', isbn: '978-0-14-101408-1'}),
        knex('books').insert({id: 6, title: 'Complete Persepolis', synopsis: 'Edgy, searingly observant, and candid, often heartbreaking but threaded throughout with raw humor and hard-earned wisdom--Persepolis is a stunning work from one of the most highly regarded, singularly talented graphic artists at work today.', genre_id:5, cover_art: 'images/complete persepolis.jpg', isbn: '978-0-78-483401-5'}),
        knex('books').insert({id: 7, title: 'Consciousness Explained', synopsis: 'Advances a new theory of consciousness based on insights gleaned from the fields of neuroscience, psychology, and artificial intelligence, and clears away obsolete myths about the process of thinking in conscious beings.', genre_id:4, cover_art: 'images/consciousness explained.jpg', isbn: '978-2-73-810216-4'}),
        knex('books').insert({id: 8, title: 'Do Androids Dream of Electric Sheep', synopsis: 'It was January 2021, and Rick Deckard had a license to kill. Somewhere among the hordes of humans out there, lurked several rogue androids. Deckards assignmet--find them and then..."retire" them. Trouble was, the androids all looked exactly like humans, and they didnt want to be found!', genre_id:1, cover_art: 'images/do androids dream of electric sheep.jpg', isbn: '978-8-83-471413-3'}),
        knex('books').insert({id: 9, title: 'Fun Home', synopsis: 'Distant and exacting, Bruce Bechdel was an English teacher and director of the town funeral home, which Alison and her family referred to as the Fun Home. It was not until college that Alison, who had recently come out as a lesbian, discovered that her father was also gay. A few weeks after this revelation, he was dead, leaving a legacy of mystery for his daughter to resolve.', genre_id:5, cover_art: 'images/fun home.jpg', isbn: '978-8-49-867123-0'}),
        knex('books').insert({id: 10, title: 'Ghost World', synopsis: 'Daniel Clowes is one of the most respected cartoonists of his generation, and Ghost World is his magnum opus. Adapted into a major motion picture directed by Terry Zwigoff (director of the acclaimed documentary Crumb), which was nominated for an Academy Award for Best Adapted Screenplay. This graphic novel is a must for any self-respecting comics fans library.', genre_id:5, cover_art: 'images/ghost world.jpg', isbn: '978-3-93-137724-3'}),
        knex('books').insert({id: 11, title: 'Grapes of Wrath', synopsis: 'A portrait of the conflict between the powerful and the powerless, of one man’s fierce reaction to injustice, and of one woman’s stoical strength, the novel captures the horrors of the Great Depression and probes the very nature of equality and justice in America.', genre_id:3, cover_art: 'images/grapes of wrath.jpg', isbn: '978-0-23-003105-0'}),
        knex('books').insert({id: 12, title: 'Hera Lindsay Bird', synopsis: 'This impressive debut has established Hera Lindsay Bird as a good girl with many beneficial thoughts and feelings. With themes as varied as snow and tears, the poems in this collection shine with the fantastic cream of who she is juxtaposing many classical and modern breezes. This is at once an intelligent and compelling fantasy of tenderness.', genre_id:2, cover_art: 'images/hera lindsay bird.jpg', isbn: '978-1-77-656071-4'}),
        knex('books').insert({id: 13, title: 'Mrs Dalloway', synopsis: 'Created from two short stories, "Mrs Dalloway in Bond Street" and the unfinished "The Prime Minister," the novel addresses Clarissas preparations for a party she will host that evening. With an interior perspective, the story travels forwards and back in time and in and out of the characters minds to construct an image of Clarissas life and of the inter-war social structure. In October 2005, Mrs. Dalloway was included on TIME magazines list of the 100 best English-language novels written since 1genre_id:23.', genre_id:3, cover_art: 'images/mrs dalloway.jpg', isbn: '978-6-61-309912-9'}),
        knex('books').insert({id: 14, title: 'Neu-Romancer', synopsis: 'Case had been the sharpest data-thief in the business, until vengeful former employers crippled his nervous system. But now a new and very mysterious employer recruits him for a last-chance run. The target: an unthinkably powerful artificial intelligence orbiting Earth in service of the sinister Tessier-Ashpool business clan. With a dead man riding shotgun and Molly, mirror-eyed street-samurai, to watch his back, Case embarks on an adventure that ups the ante on an entire genre of fiction.', genre_id:1, cover_art: 'images/neu-romancer', isbn: '978-8-08-560127-5'}),
        knex('books').insert({id: 15, title: 'The Left Hand of Darkness', synopsis: 'A groundbreaking work of science fiction, The Left Hand of Darkness tells the story of a lone human emissary to Winter, an alien world whose inhabitants can choose -and change - their gender. His goal is to facilitate Winters inclusion in a growing intergalactic civilization. But to do so he must bridge the gulf between his own views and those of the completely dissimilar culture that he encounters.', genre_id:1, cover_art: 'images/the left hand of darkeness', isbn: '978-2-74-414377-9'}),
        knex('books').insert({id: 16, title: 'The Republic', synopsis: 'Presented in the form of a dialogue between Socrates and three different interlocutors, this classic text is an enquiry into the notion of a perfect community and the ideal individual within it. During the conversation, other questions are raised: what is goodness?; what is reality?; and what is knowledge? The Republic also addresses the purpose of education and the role of both women and men as guardians of the people. With remarkable lucidity and deft use of allegory, Plato arrives at a depiction of a state bound by harmony and ruled by philosopher kings.', genre_id:4, cover_art: 'images/the republic.jpg', isbn: '978-0-75-832020-9'}),
        knex('books').insert({id: 17, title: 'The Second Sex', synopsis: 'Newly translated and unabridged in English for the first time, Simone de Beauvoir’s masterwork is a powerful analysis of the Western notion of “woman,” and a groundbreaking exploration of inequality and otherness.  This long-awaited new edition reinstates significant portions of the original French text that were cut in the first English translation. Vital and groundbreaking, Beauvoir’s pioneering and impressive text remains as pertinent today as it was sixty years ago, and will continue to provoke and inspire generations of men and women to come.', genre_id:4, cover_art: 'images/the second sex.jpg', isbn: '978-2-74-531209-9'}),
        knex('books').insert({id: 18, title: 'The Time Machine', synopsis: 'So begins the Time Traveller’s astonishing firsthand account of his journey 800,000 years beyond his own era—and the story that launched H.G. Wells’s successful career and earned him his reputation as the father of science fiction. With a speculative leap that still fires the imagination, Wells sends his brave explorer to face a future burdened with our greatest hopes...and our darkest fears.', genre_id:1, cover_art: 'images/the time machine.jpg', isbn: '978-1-90-681433-5'}),
        knex('books').insert({id: 19, title: 'Ulysses', synopsis: 'The revised edition follows the complete and unabridged text of ULYSSES as corrected and reset in 1genre_id:61. Like the first American edition of 1genre_id:34, it also contains the original foreword by the genre_id and the historic court ruling by Judge John M. Woolsey to remove the federal ban on ULYSSES. It also contains page references to the 1genre_id:34 edition, which are indicated in the margins.', genre_id:3, cover_art: 'images/ulysses.jpg', isbn: '978-8-85-413934-3'}),
        knex('books').insert({id: 20, title: 'Wuthering Heights', synopsis: 'Wuthering Heights is a wild, passionate story of the intense and almost demonic love between Catherine Earnshaw and Heathcliff, a foundling adopted by Catherines father. After Mr Earnshaws death, Heathcliff is bullied and humiliated by Catherines brother Hindley and wrongly believing that his love for Catherine is not reciprocated, leaves Wuthering Heights, only to return years later as a wealthy and polished man. He proceeds to exact a terrible revenge for his former miseries. The action of the story is chaotic and unremittingly violent, but the accomplished handling of a complex structure, the evocative descriptions of the lonely moorland setting and the poetic grandeur of vision combine to make this unique novel a masterpiece of English literature.', genre_id:3, cover_art: 'images/wuthering heights.jpg', isbn: '978-8-63-330005-6'})
      ]);
    });
};
